---
body:
  - type: markdown
    attributes:
      value: >
        Thank you for wanting to help us improve the Mullvad VPN app by suggesting a new feature!

  - type: textarea
    id: new-feature
    attributes:
      label: Feature description
      description: >
        Please describe the feature you would like to see added to the app. Also describe your setup and
        use-case that makes this feature important to you.
    validations:
      required: true

  - type: textarea
    id: other-solutions
    attributes:
      label: Alternative solutions
      description: >
        What other ways have you tried to achieve similar results? Or if this feature cannot be
        added to the app, what alternative ways do you see for moving forward?
    validations:
      required: true

  - type: checkboxes
    id: feature-area
    attributes:
      label: Type of feature
      description: In what way would the app be improved by adding this feature?
      options:
        - label: Better privacy/anonymity
        - label: Better at circumventing censorship
        - label: Easier to use
        - label: Other

  - type: checkboxes
    id: os
    attributes:
      label: Operating System
      description: On what operating system(s) do you think this feature is relevant?
      options:
        - label: Android
        - label: iOS
        - label: Windows
        - label: macOS
        - label: Linux
    validations:
      required: true
