[package]
name = "talpid-platform-metadata"
description = "Platform metadata detection functions"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
publish.workspace = true


[target.'cfg(target_os = "linux")'.dependencies]
rs-release = "0.1.7"
talpid-dbus = { path = "../talpid-dbus" }

[target.'cfg(target_os = "windows")'.dependencies.windows-sys]
version = "0.45.0"
features = [
    "Win32_Foundation",
    "Win32_System_LibraryLoader",
    "Win32_System_SystemInformation",
    "Win32_System_SystemServices",
]
