# See repository root `osv-scanner.toml` for instructions and rules for this file.

# rexml: The REXML gem before 3.3.6 has a DoS vulnerability when it parses an XML
# that has many deep elements that have same local name attributes.
[[IgnoredVulns]]
id = "CVE-2024-43398" # GHSA-952p-6rrq-rcjv
ignoreUntil = 2024-11-23
reason = "rexml only parses trusted input (responses from Apple's APIs) in this code"
