---
name: Android - Audit dependencies
on:
  pull_request:
    paths: [.github/workflows/android-audit.yml, android/gradle/verification-metadata.xml]
  schedule:
    # At 06:20 UTC every day.
    # Notifications for scheduled workflows are sent to the user who last modified the cron
    # syntax in the workflow file. If you update this you must have notifications for
    # Github Actions enabled, so these don't go unnoticed.
    # https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/notifications-for-workflow-runs
    - cron: '20 6 * * *'
  workflow_dispatch:
jobs:
  owasp-dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run gradle audit task
        run: |-
          cd android
          ./gradlew dependencyCheckAnalyze
