---
name: Rust - Audit dependencies
on:
  pull_request:
    paths:
      - .github/workflows/cargo-audit.yml
      - Cargo.lock
      - test/Cargo.lock
  schedule:
    # At 06:20 UTC every day. Will create an issue if a CVE is found.
    - cron: '20 6 * * *'
  workflow_dispatch:

permissions:
  issues: write

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions-rust-lang/audit@531fba54daed81c23724925a1892a60c74969c38 # v1.2.1
        name: Audit Rust Dependencies
        with:
          file: Cargo.lock
          denyWarnings: true
          # Ignored audit issues. This list should be kept short, and effort should be
          # put into removing items from the list.

      - uses: actions-rust-lang/audit@531fba54daed81c23724925a1892a60c74969c38 # v1.2.1
        name: Audit testrunner Rust Dependencies
        with:
          file: test/Cargo.lock
          denyWarnings: true
          # Ignored audit issues. This list should be kept short, and effort should be
          # put into removing items from the list.
