---
name: Bidirectional Unicode scan
on: [pull_request, workflow_dispatch]

permissions: {}

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout submodules
        run: git submodule update --init --depth=1 dist-assets/binaries wireguard-go-rs

      - name: Scan for code points
        run: ./ci/check-trojan-source.sh .
