[package]
name = "talpid-time"
description = "Time functions"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
tokio = { version = "1.8", features = ["time"] }
libc = "0.2"
